frontend:
  image:
    repository: aurora74/url-shorten-frontend
    tag: v0.0.9-argocd-health
  service:
    type: NodePort
    nodePort: 30080
  runtimeConfig:
    apiBaseUrl: http://192.168.130.88:30081
    publicBaseUrl: http://192.168.130.88:30080

api:
  image:
    repository: aurora74/url-shorten-api
    tag: v0.0.9-argocd-health
  service:
    type: NodePort
    nodePort: 30081
  env:
    redisMode: single
    redisAddrs: redis://url-shorten-redis:6379
  secrets:
    urlDsn:
      name: url-shorten-dev-runtime
      key: URL_DSN
    riverDsn:
      name: url-shorten-dev-runtime
      key: RIVER_DSN
    rabbitmqUrl:
      name: url-shorten-dev-runtime
      key: RABBITMQ_URL

backgroundWorker:
  image:
    repository: aurora74/url-shorten-worker
    tag: v0.0.9-argocd-health
  secrets:
    urlDsn:
      name: url-shorten-dev-runtime
      key: URL_DSN
    riverDsn:
      name: url-shorten-dev-runtime
      key: RIVER_DSN

fraudWorker:
  image:
    repository: aurora74/url-shorten-fraud
    tag: v0.0.9-argocd-health
  secrets:
    urlDsn:
      name: url-shorten-dev-runtime
      key: URL_DSN
    rabbitmqUrl:
      name: url-shorten-dev-runtime
      key: RABBITMQ_URL
    virusTotalApiKey:
      name: url-shorten-dev-runtime
      key: VIRUSTOTAL_API_KEY

dependencies:
  redis:
    enabled: true
  postgresApp:
    enabled: true
    passwordSecret:
      name: url-shorten-dev-dependencies
      key: APP_POSTGRES_PASSWORD
  postgresRiver:
    enabled: true
    passwordSecret:
      name: url-shorten-dev-dependencies
      key: RIVER_POSTGRES_PASSWORD
  rabbitmq:
    enabled: true
    passwordSecret:
      name: url-shorten-dev-dependencies
      key: RABBITMQ_PASSWORD
    erlangCookieSecret:
      name: url-shorten-dev-dependencies
      key: RABBITMQ_ERLANG_COOKIE
